### ISSUE TITLE
Fix warning of uninitialized instance variable

### ISSUE THREAD

**Issue by mojavelinux** [pepijnve/asciimath#1]
Fix the following warning caused by an uninitialized instance variable:

```
lib/asciimath/parser.rb:76: warning: instance variable @push_back not initialized
```

This shows up when running the main Asciidoctor test suite.

**Comment by pepijnve** [comment]
Resolve by ecb9954d1fb31df58988692c4196de5635ef54d0

**Comment by mojavelinux** [comment]
I see this is resolved, but it doesn't seem to be included in the 1.0.1 release on RubyGems.org. Perhaps cut a 1.0.2 release, then close.

**Comment by pepijnve** [comment]
I'm looking at the commit log and shell history and can't figure out how this went wrong... Weird.
Anyway a 1.0.2 release will be the easiest fix. I'll double check everything and do that right away.

**Comment by pepijnve** [comment]
[1.0.2 has been published](https://rubygems.org/gems/asciimath/versions/1.0.2)

**Comment by mojavelinux** [comment]
Thanks!!
